# Run Images
FROM python:3.14-slim-trixie
# アプリケーションディレクトリ名指定
ARG APPNAME=fastapi_app
# Pythonの実行環境補完
## uvインストール
RUN --mount=type=cache,mode=0755,target=/root/.cache/pip \
    pip install uv \
    && mkdir -p /usr/local/uv \
    && uv venv /usr/local/uv \
    && chmod -R 777 /usr/local \
    && echo "export UV_PROJECT_ENVIRONMENT=/usr/local/uv" >> /etc/bash.bashrc  \
    && echo "export PATH=\"/usr/local/uv/bin:\$PATH\"" >> /etc/bash.bashrc 

# Playwrightインストール
## 日本語ロケール、Notoフォントインストール
# RUN --mount=type=cache,target=/var/cache/apt \
#     --mount=type=cache,target=/var/lib/apt \
#     apt-get update \
#     && apt-get install -y --no-install-recommends locales-all fonts-noto fonts-noto-cjk \
#     && echo "export LANG=ja_JP.UTF-8" >> ~/.bashrc
# ## Playwright用のブラウザ依存関係解決
# RUN --mount=type=cache,mode=0755,target=/root/.cache/pip \
#     pip install playwright -t /tmp/ \
#     && PYTHONPATH=/tmp /tmp/bin/playwright install-deps \
#     && rm -rf /tmp/*

# Install OS packages
ARG APT_CACHE_ID=apt-cache
RUN --mount=type=cache,id=${APT_CACHE_ID},target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=${APT_CACHE_ID},target=/var/lib/apt,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends sudo curl vim git inotify-tools postgresql-client 

# initファイルのコピー
COPY ./auxiliary/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
RUN chmod +x /usr/bin/docker-entrypoint.sh


# vscodeのユーザーを追加
# 実行ユーザー追加
ARG USERNAME=vscode
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -f -g $GROUP_ID $USERNAME || true\
    && useradd -m -s /bin/bash -u $USER_ID -g $GROUP_ID $USERNAME \
    && usermod -a -G $GROUP_ID $USERNAME \
    && mkdir -p /vscode/vscode-server/ \
    && chown $USERNAME:dialout /vscode/vscode-server/.*

# アプリケーションディレクトリ作成/権限変更
RUN mkdir -p /work/$APPNAME/ 
RUN chown $USERNAME:dialout /work/$APPNAME/ \
    && chown $USERNAME:dialout /work/$APPNAME/.* 
WORKDIR /work/$APPNAME

### Python用短縮コマンド/ホットリロードシェルスクリプトを追加
COPY ./auxiliary/pythonWatch.sh /usr/local/bin/
RUN echo 'alias py="python"' >> /etc/bash.bashrc \
    && echo 'alias pyw="pythonWatch.sh"' >> /etc/bash.bashrc \
    && echo 'export pyt="python -m pytest"' >> /etc/bash.bashrc \
    && echo 'export pytest="python -m pytest"' >> /etc/bash.bashrc

EXPOSE 8000
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
## unicon起動用(uvicorn app:app --reload --host 0.0.0.0 --port 8000)
# CMD ["uvicorn", "app:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
## Gunicorn起動用(gunicorn --config ./src/gunicorn.conf.py)
# CMD ["gunicorn" ,"--config", "./src/gunicorn.conf.py"]
## デバック用
CMD [ "tail", "-f", "/dev/null"]
