# React App set Nginx
FROM nginx
LABEL  maintainer "y.yoshimoto"
# コンテツファイルの設置ディレクトリ作成
RUN mkdir -p /usr/share/nginx/html/dist \
    && chmod -R 755 /usr/share/nginx/html
    # nginx設定ファイルの設置
COPY ./rproxy.conf /etc/nginx/conf.d/default.conf
# コンテナ実行時の動作設定
EXPOSE 80 443
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
